FROM ubuntu:bionic

RUN apt-get update && apt-get install -y \
    # Utils
    iproute2 iputils-ping net-tools vim-tiny jshon telnet curl \
    # VPP package dependencies
    libnuma1 libssl1.0.0  libmbedtls10 libmbedx509-0 \
    # Honeycomb package dependencies
    openjdk-8-jre-headless \
    gdb vim python3 vim

# Disable DPDK for PCI devices

# Reduce image size
RUN rm -rf /var/lib/apt/lists/* `# clear apt cache` \
&& rm -rf packages
