#!/bin/bash

if [ "$UID" -ne 0 ]
then
    CALLER_USER=`whoami`  
    uid=$(id -u ${CALLER_USER})
    gid=$(id -g ${CALLER_USER})
    sudo gid=$gid uid=$uid CALLER_USER=${CALLER_USER} "$0" "$@"
    exit
else
    if [ -z "$CALLER_USER" ]
    then 
        echo "****** Please use non-root account  and without sudo"
        exit
    fi
fi

#Check if docker can be started wthout sudo
echo "*** Please ensure user name is added to docker group"
echo "*** you should be able to start stop docker without sudo"
#https://medium.com/devgorilla/how-to-install-docker-on-ubuntu-18-04-495216a16092

#TODO
DOCKER_IMAGE="granjan/vpp-build-env:three"

INSTALLATION_MODE=1
INSTALLATION_PATH="/usr/bin"
BUILDER_CREATE="vpp_build_builder_create"
#This is just temporary
BUILD_ALL="vpp_build_build_all"
SCRIPT=$(readlink -f $0)
BASE_DIR=`dirname $SCRIPT`

VPP_WS="/home/${CALLER_USER}/VPP-WS/"
VPP_WS_KITCHEN="KITCHEN"

if [ "$BASE_DIR" == "$INSTALLATION_PATH" ]
then
    INSTALLATION_MODE=0
else
    echo 
    echo "  Files will get installed in $INSTALLATION_PATH"
    INSTALLATION_MODE=1

    echo "  VPP Build env installation starting ....."
    echo  
    echo "  Creating VPP workspace directory @ $VPP_WS"
    mkdir -p $VPP_WS

    KITCHEN="$VPP_WS/$VPP_WS_KITCHEN"
    echo
    echo "  Creating VPP workspace kitchen sink @ $KITCHEN"
    echo "      This directory will have small scripts"
    echo "  like toplogy etc dictating topology, vpp configs etc"
    mkdir -p $KITCHEN
    chown $uid:$gid $KITCHEN
    
    echo   
    echo "  Copying example build scipts @$KITCHEN "
    echo "  ---Run vpp_build_one_time_run once for setting maven for honeycomb build"
    cp  $BASE_DIR/vpp_build_one_time_run $KITCHEN
    
    echo "  ---See vpp_build_build_all on how build is done"
    cp  $BASE_DIR/vpp_build_build_all $KITCHEN

    chown $uid:$gid $VPP_WS
    chown  $uid:$gid $KITCHEN
    chown  $uid:$gid $KITCHEN/vpp_build_one_time_run
    chown  $uid:$gid $KITCHEN/vpp_build_build_all
    
    BUILDER_FILE=$INSTALLATION_PATH/$BUILDER_CREATE
    cp -f $(readlink -f $0) $BUILDER_FILE
    echo "  ----Please use $BUILDER_FILE for creating build"
    echo "      deploy env after this installation deploy"
 
    #let us fix the username used for docker
    BUILDER_CONNECT="vpp_build_builder_connect"
    echo "  ---Use $BUILDER_CONNECT to connect to your build environment"
    echo "docker exec -u $CALLER_USER -it builder "/bin/bash" "  > $INSTALLATION_PATH/$BUILDER_CONNECT
    
    BUILDER_STOP="vpp_build_builder_stop"
    echo "  ---Use $BUILDER_STOP to stop vpp build env"
    echo "docker stop builder"  > $INSTALLATION_PATH/$BUILDER_STOP

    BUILDER_RM="vpp_build_builder_rm"
    echo "  ---Use $BUILDER_STOP to remove vpp build env"
    echo "docker rm builder"  > $INSTALLATION_PATH/$BUILDER_RM

    chmod +x $INSTALLATION_PATH/vpp_build_builder_*
    chown -R $uid:$gid $INSTALLATION_PATH/vpp_build_builder_*

    echo "  Pulling Docker image $DOCKER_IMAGE"
    docker pull $DOCKER_IMAGE
    exit
fi

export VPP_WS=$VPP_WS
export NAME=$CALLER_USER
export uid=$uid
export gid=$gid

echo 
echo "  Removing any build any older build environment"
docker stop  builder
docker rm    builder
docker run \
    --privileged \
    -v $VPP_WS:$VPP_WS  \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --name builder \
    -td $DOCKER_IMAGE   \
    /bin/bash 
      

echo "  Removing fixing the image ...."
docker exec -it builder /bin/bash -c " \
                  mkdir -p  /home/gyan;\
                  touch /etc/passwd;\
                  touch /etc/group; \
                  groupadd $gid;  \
                  hostname builder;  \
                  useradd -rm -d /home/$NAME -s /bin/bash -g $gid  -G sudo  -u $uid $NAME;\
                  chown $uid:$gid /home/$NAME; \
                  echo $NAME:U6aMy0wojraho |  chpasswd -e ;\
                  echo \"$NAME ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers "

echo "  netns exopsed ...."
pid=`docker inspect -f '{{.State.Pid}}' builder`
mkdir -p /var/run/netns/
rm -f /var/run/netns/builder
ln -s "/proc/$pid/ns/net" /var/run/netns/builder

